### ISSUE TITLE
only the first element added to a set is draggable

### ISSUE THREAD

**Issue by leedo** [mephraim/raphael.draggable#2]
If I add multiple items to a set, only the first item in the set actually starts a drag. The other items are dragged along with it, but clicking on them does not start a drag.

**Comment by leedo** [comment]
http://gist.github.com/402653

is an example

**Comment by leedo** [comment]
this fix works for me:
http://github.com/leedo/raphael.draggable/commit/c2a445c59a674353d57cf2efa3c16a63610ea814

**Comment by mephraim** [comment]
thanks for the fix! I just pulled in the changes. I think when I originally was writing the draggable code, the push function only took one parameter. I hadn't made many updates since the push function was updated.
